### ISSUE TITLE
formOnly not working

### ISSUE THREAD

**Issue by rodrigof1307** [halilb/rn-credit-card#12]
Hey I tried to set the formOnly prop however the editor says it doesn't exist. Where should I add it to activate it?
<img width="1440" alt="Captura de ecrã 2021-10-07, às 18 18 11" src="https://user-images.githubusercontent.com/46696312/136432988-cdb40699-9abe-4637-8ae5-a41b37a193b5.png">
<img width="1440" alt="Captura de ecrã 2021-10-07, às 18 18 13" src="https://user-images.githubusercontent.com/46696312/136433000-b45ba666-8a9b-4618-8e38-9db8f6366401.png">

**Comment by halilb** [comment]
Hmm, that's weird. The code looks correct, and `formOnly` is defined here: https://github.com/halilb/rn-credit-card/blob/f6e51ad00b9aa5b04b13d9dab9f6e66cbff8628c/src/types.ts#L68

Does it hide the card view on the screen when you pass `formOnly`?

**Comment by rodrigof1307** [comment]
No, I can't set formOnly because it is not included on the libraryProps as you can see here. Do I have to install a different library/version? The current version I have is  "rn-credit-card": "^1.0.2" 
<img width="1440" alt="Captura de ecrã 2021-10-08, às 15 11 20" src="https://user-images.githubusercontent.com/46696312/136572143-45b37f74-b158-4924-963b-80e4071490b3.png">

**Comment by halilb** [comment]
Oh. I think the latest code was not published on npm by mistake.

I just released version `1.0.4`. Could you try that one and let me know?

**Comment by halilb** [comment]
This should be fixed with `1.0.4` version.
