### ISSUE TITLE
use default fonts not expp google fonts

### ISSUE THREAD

**Issue by ghost** [halilb/rn-credit-card#19]
i am using React native CLI, Not Expo .
thus i wanna use defult installed fonts of my app, how can i achieve that ?!
![simulator_screenshot_8A9065B0-FFEF-40AB-8CE5-E12D991252C4](https://user-images.githubusercontent.com/8994555/194863583-9a8331b7-18b5-4556-81bc-e3d9c11a803d.png)

**Comment by halilb** [comment]
Have you tried configuring them through the `fonts` prop? https://github.com/halilb/rn-credit-card#fonts

```tsx
<CreditCardForm
  fonts={{
    regular: 'RobotoMono_400Regular',
    bold: 'RobotoMono_700Bold',
  }}
/>
```

**Comment by ghost** [comment]
i used 
<CreditCardForm
  fonts={{
    regular: 'cairo_font_regular',
    bold: 'cairo_font_bold',
  }}
/>

but no luck !

**Comment by halilb** [comment]
Please make sure those fonts are loaded fine on your app. You may test them with `Text` component:

```tsx
import { Text } from 'react-native';

return (    
  <Text style={{ fontFamily: 'cairo_font_regular' }}>
    Test
  </Text>
);
```

**Comment by ghost** [comment]
thanks,i used this method, it worked like a charm
you can close this issue , thanks again .
![simulator_screenshot_8F47E8A0-9BDE-4FED-9BC2-94ABF6E36859](https://user-images.githubusercontent.com/8994555/194889158-056f8181-4132-4d57-aadc-94d06c382d98.png)
