### ISSUE TITLE
Show all Input Fields together

### ISSUE THREAD

**Issue by fadiaIW** [halilb/rn-credit-card#9]
Hi,
This is a lovely repo. Thanks for this! 
My project requires me to show all the input fields together (instead of one sliding in after the other) . Is that possible ( Im sure it is, just cant figure out how!) ? 

Thanks!

**Comment by halilb** [comment]
Hi @fadiaIW,

Checkout `formOnly` props. It should be what you're looking for: https://github.com/halilb/rn-credit-card#formonly

**Comment by fadiaIW** [comment]
> Hi @fadiaIW,
> 
> Checkout `formOnly` props. It should be what you're looking for: https://github.com/halilb/rn-credit-card#formonly

I think you meant horizontalState. Worked perfectly! Thanks! 
Also, is it possible if i use textInput from react-native directly. So as to make my entire form ( additional fields in the project) with a consistent UI? 

Thanks for the instant response! Appreciate it :)

**Comment by halilb** [comment]
> I think you meant horizontalState. Worked perfectly! Thanks!

Oh right, I meant `horizontalStart`.

> Also, is it possible if i use textInput from react-native directly. So as to make my entire form ( additional fields in the project) with a consistent UI?

I'm afraid that's not possible. Your best bet would be forking the repo and making the changes you need.
